export type Product = {
  id: number | string;
  name: string;
  slug: string;
  category: string;
  categorySlug: string;
  detail: string;
  description: string;
  image: string;
  images: string[];
  lengths: string[];
  weights: string[];
  price: string;
  priceNote: string;
};

export type Category = {
  name: string;
  slug: string;
  image: string;
  description: string;
  group: string;
};

export const whatsappNumber = '2349121325113';
export const whatsappLink = (message: string) =>
  `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

export const categories: Category[] = [
  {
    name: 'Luxury Human Hair',
    slug: 'luxury-human-hair',
    image: '/images/products/Human hair.jpeg',
    description: 'Premium, carefully selected human hair for the woman who values quality above all.',
    group: 'Hair',
  },
  {
    name: 'Raw Donor Hair',
    slug: 'raw-donor-hair',
    image: '/images/products/Raw donor bounce.jpeg',
    description: 'Unprocessed raw donor hair with intact cuticles for the most natural look and feel.',
    group: 'Hair',
  },
  {
    name: 'Bone Straight',
    slug: 'bone-straight',
    image: '/images/products/Raw Vietnamese bone straight.jpeg',
    description: 'Sleek, straight, and effortlessly elegant — the definition of timeless.',
    group: 'Hair',
  },
  {
    name: 'Deep Wave',
    slug: 'deep-wave',
    image: '/images/products/16 inches SDD pixie curls.jpeg',
    description: 'Voluminous deep waves that hold their bounce and beauty wash after wash.',
    group: 'Hair',
  },
  {
    name: 'Omotola bounce piano color',
    slug: 'body-wave',
    image: '/images/products/Omotola bounce piano color.jpeg',
    description: 'Soft, flowing waves that frame the face with effortless grace.',
    group: 'Hair',
  },
  {
    name: 'Curly Hair',
    slug: 'curly-hair',
    image: '/images/products/16 inches SDD pixie curls.jpeg',
    description: 'Beautifully defined curls with natural volume and movement.',
    group: 'Hair',
  },
  {
    name: 'Luxury Wigs',
    slug: 'luxury-wigs',
    image: '/images/products/Raw unit 30 inches pixie curls.jpeg',
    description: 'Ready-to-wear and custom luxury wigs, crafted for a flawless finish.',
    group: 'Wigs',
  },
  {
    name: 'Frontal Wigs',
    slug: 'frontal-wigs',
    image: '/images/products/10 inches 200 grams wide 5by5 closure..jpeg',
    description: 'Ear-to-ear lace frontal wigs for the most natural, seamless hairline.',
    group: 'Wigs',
  },
  {
    name: 'Closure Wigs',
    slug: 'closure-wigs',
    image: '/images/products/10 inches with 5by5 closure.jpeg',
    description: 'Beautifully crafted closure wigs for a natural, versatile look.',
    group: 'Wigs',
  },
  {
    name: 'Wig Making Tools',
    slug: 'wig-making-tools',
    image: '/images/products/product_3.jpeg',
    description: 'Professional-grade tools for wig makers — needles, caps, stands, and more.',
    group: 'Tools & Care',
  },
  {
    name: 'Wig Care Products',
    slug: 'wig-care-products',
    image: '/images/products/product_1.jpeg',
    description: 'Shampoos, conditioners, sprays, and serums to keep your wigs luxurious.',
    group: 'Tools & Care',
  },
  {
    name: 'Wig Accessories',
    slug: 'wig-accessories',
    image: '/images/products/product_4.jpeg',
    description: 'Brushes, combs, satin bonnets, and storage to protect your investment.',
    group: 'Tools & Care',
  },
];

export const products: Product[] = [
  {
    id: 21,
    name: 'Human Hair',
    slug: 'human-hair',
    category: 'Luxury Human Hair',
    categorySlug: 'luxury-human-hair',
    detail: 'Premium human hair',
    description: 'Premium, carefully selected human hair with a soft, natural finish and lasting quality.',
    image: '/images/products/Human hair.jpeg',
    images: ['/images/products/Human hair.jpeg'],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
    weights: ['100g', '200g', '300g'],
    price: '₦26,500',
    priceNote: 'Fixed price.',
  },
  {
    id: 1,
    name: 'Omotola bounce piano color',
    slug: 'Omotola bounce piano color',
    category: 'Omotola bounce piano color',
    categorySlug: 'Omotola bounce piano color',
    detail: 'Raw donor hair · 8–30 inches',
    description: 'Our signature body wave is crafted from 100% raw donor hair with intact cuticles, offering soft, flowing waves that frame the face with effortless grace. Each bundle is carefully selected and processed to maintain its natural luster and strength.',
    image: '/images/products/Omotola bounce piano color.jpeg',
    images: [
      '/images/products/Omotola bounce piano color.jpeg',
      '/images/products/Raw donor bounce.jpeg',
      '/images/products/Human hair.jpeg',
    ],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"','30"'],
    weights: ['100g', '200g', '300g'],
    price: '₦75,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 2,
    name: 'The Sivia Curl Edit',
    slug: 'the-sivia-curl-edit',
    category: 'Luxury Wigs',
    categorySlug: 'luxury-wigs',
    detail: 'Glueless lace frontal · Custom fit',
    description: 'A glueless lace frontal wig with beautifully defined curls, custom-fitted to your head measurements for a flawless, natural look. Pre-plucked hairline, bleached knots, and an adjustable band for secure, comfortable wear.',
    image: '/images/products/Raw unit 30 inches pixie curls.jpeg',
    images: [
      '/images/products/Raw unit 30 inches pixie curls.jpeg',
      '/images/products/Raw unit 28 inches pixie curls.jpeg',
      '/images/products/16 inches SDD pixie curls.jpeg',
    ],
    lengths: ['14"', '16"', '18"', '20"', '22"', '24"'],
    weights: ['150g', '180g', '210g'],
    price: 'Contact for price',
    priceNote: 'Price varies by length, weight and style. Contact us for current pricing.',
  },
  {
    id: 3,
    name: 'Miracle Hair Elixir',
    slug: 'miracle-hair-elixir',
    category: 'Wig Care Products',
    categorySlug: 'wig-care-products',
    detail: '14-in-1 moisture & shine treatment',
    description: 'Our signature 14-in-1 miracle elixir delivers deep moisture, brilliant shine, frizz control, and heat protection in one luxurious formula. Suitable for both natural hair and luxury wigs.',
    image: '/images/products/product_1.jpeg',
    images: ['/images/products/product_1.jpeg', '/images/products/product_4.jpeg'],
    lengths: ['100ml', '250ml', '500ml'],
    weights: ['Standard'],
    price: 'Contact for price',
    priceNote: 'Contact us for current pricing.',
  },
  {
    id: 4,
    name: 'Salon Styling Brush',
    slug: 'salon-styling-brush',
    category: 'Wig Making Tools',
    categorySlug: 'wig-making-tools',
    detail: 'Professional heat styling brush',
    description: 'A professional-grade styling brush designed for use with luxury wigs and extensions. Heat-resistant bristles, ergonomic handle, and gentle detangling for smooth, polished results every time.',
    image: '/images/products/Hair straightener brush.jpeg',
    images: ['/images/products/product_3.jpeg'],
    lengths: ['Medium', 'Large'],
    weights: ['Standard'],
    price: '₦18,500',
    priceNote: 'Fixed price.',
  },
  {
    id: 5,
    name: 'Raw Donor Deep Wave',
    slug: 'raw-donor-deep-wave',
    category: 'Pixie Curls',
    categorySlug: 'pixie-curls',
    detail: 'Unprocessed raw hair · 8–30 inches',
    description: 'Unprocessed raw donor deep wave hair with intact cuticles for the most natural look and feel. Voluminous, bouncy waves that hold their pattern wash after wash.',
    image: '/images/products/16 inches SDD pixie curls.jpeg',
    images: [
      '/images/products/16 inches SDD pixie curls.jpeg',
      '/images/products/Raw donor bounce.jpeg',
    ],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
    weights: ['100g', '200g', '300g'],
    price: '₦250,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 6,
    name: 'Bone Straight Luxury',
    slug: 'bone-straight-luxury',
    category: 'Bone Straight',
    categorySlug: 'bone-straight',
    detail: 'Sleek and straight · 8–30 inches',
    description: 'Sleek, straight, and effortlessly elegant. Our bone straight hair is the definition of timeless — smooth from root to tip with a natural sheen that catches every light.',
    image: '/images/products/Raw Vietnamese bone straight.jpeg',
    images: [
      '/images/products/Raw Vietnamese bone straight.jpeg',
      '/images/products/Human hair.jpeg',
    ],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
    weights: ['100g', '200g', '300g'],
    price: '₦300,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 7,
    name: 'Frontal Lace Wig — Blonde',
    slug: 'frontal-lace-wig-blonde',
    category: 'Frontal Wigs',
    categorySlug: 'frontal-wigs',
    detail: 'Ear-to-ear lace · 13x6 frontal',
    description: 'A stunning ear-to-ear lace frontal wig with a 13x6 frontal area for the most natural, seamless hairline. Pre-plucked, bleached knots, and baby hairs for an undetectable finish.',
    image: '/images/products/10 inches 200 grams wide 5by5 closure..jpeg',
    images: [
      '/images/products/10 inches 200 grams wide 5by5 closure..jpeg',
      '/images/products/10 inches 200 grams with 2by6 closure.jpeg',
    ],
    lengths: ['14"', '16"', '18"', '20"', '22"', '24"'],
    weights: ['150g', '180g', '210g'],
    price: 'Contact for price',
    priceNote: 'Price varies by length, weight and style. Contact us for current pricing.',
  },
  {
    id: 8,
    name: 'Closure Wig — Natural Black',
    slug: 'closure-wig-natural-black',
    category: 'Closure Wigs',
    categorySlug: 'closure-wigs',
    detail: '4x4 closure · Custom fit',
    description: 'A beautifully crafted closure wig with a 4x4 lace closure for a natural, versatile parting. Custom-fitted to your measurements with an adjustable band for secure wear.',
    image: '/images/products/10 inches with 5by5 closure.jpeg',
    images: [
      '/images/products/10 inches with 5by5 closure.jpeg',
      '/images/products/10 inches 200 grams with 2by6 closure.jpeg',
    ],
    lengths: ['14"', '16"', '18"', '20"', '22"', '24"'],
    weights: ['150g', '180g', '210g'],
    price: 'Contact for price',
    priceNote: 'Price varies by length, weight and style. Contact us for current pricing.',
  },
  {
    id: 9,
    name: 'Curly Volume Bundle',
    slug: 'curly-volume-bundle',
    category: 'Curly Hair',
    categorySlug: 'curly-hair',
    detail: 'Naturally defined curls · 8–30 inches',
    description: 'Beautifully defined curls with natural volume and movement. Our curly bundles are sourced from a single donor for consistency in curl pattern and quality.',
    image: '/images/products/16 inches SDD pixie curls.jpeg',
    images: [
      '/images/products/16 inches SDD pixie curls.jpeg',
      '/images/products/Raw unit 28 inches pixie curls.jpeg',
    ],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
    weights: ['100g', '200g', '300g'],
    price: 'Contact for price',
    priceNote: 'Price varies by length, weight and style. Contact us for current pricing.',
  },
  {
    id: 10,
    name: 'Wig Care Mousse',
    slug: 'wig-care-mousse',
    category: 'Wig Care Products',
    categorySlug: 'wig-care-products',
    detail: 'Hold & shine · Lightweight formula',
    description: 'A lightweight styling mousse that provides flexible hold and brilliant shine without weighing down your wig. Perfect for maintaining curl definition and reducing frizz.',
    image: '/images/products/product_4.jpeg',
    images: ['/images/products/product_4.jpeg', '/images/products/product_1.jpeg'],
    lengths: ['150ml', '300ml'],
    weights: ['Standard'],
    price: 'Contact for price',
    priceNote: 'Contact us for current pricing.',
  },
  {
    id: 11,
    name: 'Satin Bonnet — Gold Trim',
    slug: 'satin-bonnet-gold-trim',
    category: 'Wig Accessories',
    categorySlug: 'wig-accessories',
    detail: 'Premium satin · Protects while you sleep',
    description: 'A premium satin bonnet with elegant gold trim, designed to protect your luxury wigs and natural hair while you sleep. Reduces friction, prevents tangling, and preserves moisture.',
    image: '/images/products/product_4.jpeg',
    images: ['/images/products/product_4.jpeg'],
    lengths: ['One size', 'Large'],
    weights: ['Standard'],
    price: 'Contact for price',
    priceNote: 'Contact us for current pricing.',
  },
  {
    id: 12,
    name: 'Raw Donor Luxury Pack',
    slug: 'raw-donor-luxury-pack',
    category: 'Raw Donor Hair',
    categorySlug: 'raw-donor-hair',
    detail: '3-bundle pack · Raw unprocessed',
    description: 'Our raw donor luxury pack includes three bundles of unprocessed raw donor hair from a single donor. Intact cuticles, natural luster, and unmatched longevity for the woman who demands the very best.',
    image: '/images/products/Raw donor bounce.jpeg',
    images: [
      '/images/products/Raw donor bounce.jpeg',
      '/images/products/Human hair.jpeg',
    ],
    lengths: ['8"', '10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
    weights: ['100g', '200g', '300g'],
    price: 'Contact for price',
    priceNote: 'Price varies by length, weight and style. Contact us for current pricing.',
  },
  {
    id: 13,
    name: '10-Inch Closure Unit — 5x5',
    slug: '10-inch-5x5-closure-unit',
    category: 'Closure Wigs',
    categorySlug: 'closure-wigs',
    detail: '200g closure unit · 5x5 lace',
    description: 'A neat 10-inch closure unit with a soft, natural finish and an easy 5x5 parting space for everyday styling.',
    image: '/images/products/10 inches 200 grams wide 5by5 closure..jpeg',
    images: ['/images/products/10 inches 200 grams wide 5by5 closure..jpeg'],
    lengths: ['10"'],
    weights: ['200g'],
    price: '₦185,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 14,
    name: '10-Inch Closure Unit — 2x6',
    slug: '10-inch-2x6-closure-unit',
    category: 'Closure Wigs',
    categorySlug: 'closure-wigs',
    detail: '200g closure unit · 2x6 lace',
    description: 'A sleek 10-inch closure unit with a 2x6 lace area, made for a polished bob and simple, natural-looking parting.',
    image: '/images/products/10 inches 200 grams with 2by6 closure.jpeg',
    images: ['/images/products/10 inches 200 grams with 2by6 closure.jpeg'],
    lengths: ['10"'],
    weights: ['200g'],
    price: '₦150,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 15,
    name: '16-Inch SDD Pixie Curls',
    slug: '16-inch-sdd-pixie-curls',
    category: 'Luxury Wigs',
    categorySlug: 'luxury-wigs',
    detail: 'Defined pixie curls · 16 inches',
    description: 'A full, bouncy curly unit with defined pixie curls and rich volume for a confident statement look.',
    image: '/images/products/16 inches SDD pixie curls.jpeg',
    images: ['/images/products/16 inches SDD pixie curls.jpeg'],
    lengths: ['16"'],
    weights: ['Standard'],
    price: '₦250,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 16,
    name: 'Raw Unit Pixie Curls — 28 Inch',
    slug: 'raw-unit-pixie-curls-28-inch',
    category: 'Luxury Wigs',
    categorySlug: 'luxury-wigs',
    detail: 'Raw curly unit · 28 inches',
    description: 'A long raw curly unit with soft, defined texture, dramatic volume, and plenty of styling movement.',
    image: '/images/products/Raw unit 28 inches pixie curls.jpeg',
    images: ['/images/products/Raw unit 28 inches pixie curls.jpeg'],
    lengths: ['28"'],
    weights: ['Standard'],
    price: '₦650,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 17,
    name: 'Raw Unit Pixie Curls — 30 Inch',
    slug: 'raw-unit-pixie-curls-30-inch',
    category: 'Luxury Wigs',
    categorySlug: 'luxury-wigs',
    detail: 'Raw curly unit · 30 inches',
    description: 'A statement-length raw curly unit with dense, defined curls and a soft, luxurious finish.',
    image: '/images/products/Raw unit 30 inches pixie curls.jpeg',
    images: ['/images/products/Raw unit 30 inches pixie curls.jpeg'],
    lengths: ['30"'],
    weights: ['Standard'],
    price: '₦750,000',
    priceNote: 'Fixed price.',
  },
  {
    id: 18,
    name: 'Promozer Hair Straightener Brush',
    slug: 'promozer-hair-straightener-brush',
    category: 'Wig Making Tools',
    categorySlug: 'wig-making-tools',
    detail: 'Heated smoothing brush · Adjustable temperature',
    description: 'A heated straightening brush with adjustable temperature control for smooth, polished styling on wigs and natural hair.',
    image: '/images/products/Hair straightener brush.jpeg',
    images: ['/images/products/Hair straightener brush.jpeg'],
    lengths: ['Standard'],
    weights: ['Standard'],
    price: '₦18,500',
    priceNote: 'Fixed price.',
  },
  {
    id: 19,
    name: 'Hawaiian Silky 14-in-1 Miracle Worker',
    slug: 'hawaiian-silky-miracle-worker',
    category: 'Wig Care Products',
    categorySlug: 'wig-care-products',
    detail: 'Moisture, shine & heat protection',
    description: 'A versatile leave-in treatment that moisturizes, adds shine, reduces frizz, and helps protect hair from heat and breakage.',
    image: '/images/products/product_1.jpeg',
    images: ['/images/products/product_1.jpeg'],
    lengths: ['473ml'],
    weights: ['Standard'],
    price: 'Contact for price',
    priceNote: 'Contact us for current pricing.',
  },
  {
    id: 20,
    name: 'Aunt Jackie\'s Curl La La Custard',
    slug: 'aunt-jackies-curl-la-la-custard',
    category: 'Wig Care Products',
    categorySlug: 'wig-care-products',
    detail: 'Curl defining custard · 511g',
    description: 'A rich curl-defining custard for enhancing texture, controlling frizz, and leaving curls soft with lasting definition.',
    image: '/images/products/product_4.jpeg',
    images: ['/images/products/product_4.jpeg'],
    lengths: ['511g'],
    weights: ['Standard'],
    price: 'Contact for price',
    priceNote: 'Contact us for current pricing.',
  },
];

export const services = [
  {
    title: 'Custom Wig Making',
    description: 'A personalized unit designed around your desired look, fit and lifestyle.',
    icon: 'Sparkles',
  },
  {
    title: 'Wig Revamp & Restyling',
    description: 'Bring an old favorite back to life with expert washing, restoration and styling.',
    icon: 'Scissors',
  },
  {
    title: 'Frontal & Closure Ventilation',
    description: 'Fine, seamless ventilation for a natural hairline and luxurious finish.',
    icon: 'Star',
  },
  {
    title: 'Machine Wig Making',
    description: 'Durable, beautifully constructed machine wigs made for effortless wear.',
    icon: 'Check',
  },
];

export const testimonials = [
  { name: 'Amara E.', rating: 5, review: 'The quality of my hair was absolutely amazing. Soft, luxurious and exactly what I wanted. The Sivia team understood the assignment.' },
  { name: 'Chioma O.', rating: 5, review: 'My custom wig fit perfectly and looked so natural. I have never felt more confident. Thank you THE SIVIA NG!' },
  { name: 'Zainab A.', rating: 5, review: 'They brought my old wig back to life. I could not believe it was the same wig. Truly expert craftsmanship.' },
];

export const trainingAreas = [
  'Introduction to Wig Making',
  'Machine Wig Making',
  'Frontal & Closure Installation Techniques',
  'Ventilation',
  'Wig Construction',
  'Wig Styling',
  'Wig Revamp',
  'Wig Maintenance',
];

export const getCategoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (slug: string) => products.filter((p) => p.categorySlug === slug);

export const categoryGroups: { label: string; items: Category[] }[] = [
  { label: 'Hair', items: categories.filter((c) => c.group === 'Hair') },
  { label: 'Wigs', items: categories.filter((c) => c.group === 'Wigs') },
  { label: 'Tools & Care', items: categories.filter((c) => c.group === 'Tools & Care') },
];
